---
- name: Initial setup for the homelab cluster
  become: true
  hosts: all
  vars_files:
    - ./vars/setup_variables.yaml

  pre_tasks:
    - name: Create user
      user:
        name: '{{ ssh_user }}'
        state: present
        shell: /bin/bash
        expires: -1
        groups: sudo

    - name: Give sudo access to the user created
      copy:
        dest: '/etc/sudoers.d/{{ ssh_user }}'
        content: '{{ ssh_user }} ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

    - name: Update the system packages
      apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false

    - name: Add SSH key
      ansible.posix.authorized_key:
        user: "{{ ssh_user }}"
        state: present
        key: "{{ lookup('file', ssh_key_directory ) }}"

  tasks:
    - name: Install needed packages
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages_to_install }}"

    - name: Check if Docker is already present.
      command: which docker
      failed_when: false
      changed_when: false
      register: docker_command_result

    - name: Download Docker install convenience script
      get_url:
        url: https://get.docker.com/
        dest: /tmp/get-docker.sh
        mode: 0775
      when: docker_command_result.rc == true

    - name: Run Docker install convenience script
      command: /tmp/get-docker.sh
      environment:
        CHANNEL: stable
      when: docker_command_result.rc == true
      
    - name: Ensure Docker is started.
      service:
        name: docker
        state: started
        enabled: true
    
    - name: Install docker-compose through pip
      pip:
        name: docker-compose
        executable: pip3
        
  post_tasks:
    - name: Clean system packages
      apt:
        autoclean: true
        autoremove: true
    
    - name: restart docker
      service:
        name: docker
        state: restarted

- name: Setup the control node
  become: true
  hosts: master_node
  vars_files:
    - ./vars/setup_variables.yaml

  pre_tasks:
    - name: Set machine as the control node
      set_fact:
        k3s_control_node: true
        k3s_become_for_all: true

  roles: 
    - xanmanning.k3s 
  ignore_errors: yes

- name: Setup the worker nodes.
  become: true
  hosts: worker_nodes
  vars_files:
    - ./vars/setup_variables.yaml

  pre_tasks:
    - name: Set variables for the worker node
      set_fact:
        k3s_become_for_all: true

  roles: 
    - xanmanning.k3s
  
  ignore_errors: yes
